# nginx proxy address - http://172.17.0.1:69092


x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

name: pingvin
services:
  app:
    image: stonith404/pingvin-share:latest
    container_name: pingvin-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      CONTAINER_NAME: pingvin-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - './volumes/data/pingvin:/opt/app/backend/data'
      - './volumes/data/pingvin-images:/opt/app/frontend/public/img'
    ports:
      - 172.17.0.1:69092:3000
    networks:
      - pingvin
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://pingvin-app:3000'
      - 'cloudflare.hostname=pingvin.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.pingvin-app.entrypoints=http'
      - 'traefik.http.routers.pingvin-app-secure.tls=true'
      - 'traefik.http.routers.pingvin-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.pingvin-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.pingvin-app.middlewares=pingvin-app-https-redirect'
      - 'traefik.http.routers.pingvin-app-secure.entrypoints=https'
      - 'traefik.http.routers.pingvin-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.pingvin-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.pingvin-app-secure.service=pingvin-app'
      - 'traefik.http.services.pingvin-app.loadbalancer.server.port=3000'

networks:
  pingvin:
    name: pingvin
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
