name: pingvin
services:
  app:
    image: stonith404/pingvin-share:latest
    container_name: pingvin-app
    hostname: pingvin
    restart: always
    pull_policy: always
    volumes:
      - './rootfs/data/pingvin:/opt/app/backend/data'
      - './rootfs/data/images:/opt/app/frontend/public/img'
    ports:
      - 172.17.0.1:69092:3000
    networks:
      - pingvin

networks:
  pingvin:
    name: pingvin
    external: false
